pipeline:
  "[environment]":
    image: golang:1.19
    pull: true
    environment:
      CGO_ENABLED: "0"
    commands:
      - go version
      - go env
    volumes:
      - /build_cache/go:/go
    when:
      branch: master
  "[build]":
    image: golang:1.19
    environment:
      CGO_ENABLED: "0"
    commands:
      - go build -v -ldflags "-X main.version=" -a -tags netgo -o release/linux/amd64/drone-ansible .
    volumes:
      - /build_cache/go:/go
    when:
      branch: master
  "[docker]":
    image: docker:20.10.22
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOCKER_HOST=tcp://192.168.31.95:2375
    commands:
      - docker build -t $${DOCKER_REPO}:latest -f docker/Dockerfile.linux.amd64 .
      - docker login -u $${DOCKER_USER} -p $${DOCKER_PASSWORD} $${DOCKER_REPO}
      - docker push $DOCKER_REPO:latest
    secrets: [ docker_repo, docker_user, docker_password ]
    when:
      branch: master
depends_on:
  - testing
