pipeline:
  "[lint]":
    image: golang:1.19
    pull: true
    commands:
      - go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
      - golangci-lint version
      - golangci-lint run
    volumes:
      - name: gopath
        path: "/go"
    when:
      branch: master
  "[test]":
    image: golang:1.19
    commands:
      - go test -cover ./...
    volumes:
      - name: gopath
        path: "/go"
    when:
      branch: master
volumes:
  - name: gopath
    temp: {}
