pipeline:
  "[lint]":
    image: golang:1.19
    pull: true
    commands:
      - go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
      - golangci-lint version
      - golangci-lint run
    volumes:
      - /build_cache/go:/go
    when:
      branch: master
  "[test]":
    image: golang:1.19
    commands:
      - go test -cover ./...
    volumes:
      - /build_cache/go:/go
    when:
      branch: master
